name: ${project.parent.name}
version: ${project.parent.version}
description: ${project.description}
authors: [Gecolay]
website: https://www.spigotmc.org/resources/000000
main: ${project.parent.groupId}.${project.parent.artifactId}Main
api-version: 1.13
folia-supported: true
softdepend: [PlaceholderAPI, WorldGuard]

commands:

  gemote:

    usage: /<command> [<Emote>]
    aliases: [emote]
    description: Emote command
    permission: GEmote.Emote

  gemotereload:

    usage: /<command>
    aliases: [gemoterl]
    description: Plugin reload command
    permission: GEmote.Reload



permissions:

  GEmote.*:
    default: op
    description: GEmote | Permissions
    children:
      GEmote.Emote.*: true
      GEmote.Update: true
      GEmote.Reload: true

  GEmote.Emote.*:
    default: true
    description: Emote | Permissions
    children:
      GSit.Emote: true

  GEmote.Emote:
    default: true
    description: Emote command | Permission

  GEmote.ByPass.*:
    default: op
    description: ByPass | Permissions
    children:
      GEmote.ByPass.World: true
      GEmote.ByPass.Region: true

  GEmote.ByPass.World:
    default: op
    description: ByPass world | Permission

  GEmote.ByPass.Region:
    default: op
    description: ByPass region | Permission

  GEmote.Update:
    default: op
    description: Update notification | Permission

  GEmote.Reload:
    default: op
    description: Plugin reload command | Permission